# Generated by Django 5.2.7 on 2025-12-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.IntegerField(help_text='Enter name of the class')),
                ('stream', models.CharField(help_text='Enter stream name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_due_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Paid'), (0, 'Pending')])),
                ('academic_year', models.DateField()),
                ('term', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')])),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="Enter parent's full name", max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.IntegerField(help_text='Enter name of the subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="Enter teacher's full name", max_length=100)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('reference_number', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter first name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Enrolled', 'Student is enrolled'), ('Expelled', 'Student is expelled'), ('Suspended', 'Student is suspended'), ('Alumni', 'Student has completed'), ('Transferred', 'Student has transferred')], max_length=11)),
                ('date_of_admission', models.DateField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.grade')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.DateField()),
                ('date_enrolled', models.DateField()),
                ('date_left', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Enrolled'), (0, 'Not enrolled')])),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Present'), (0, 'Absent')])),
                ('date', models.DateField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.grade')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('M', 'Mother'), ('F', 'Father'), ('G', 'Guardian')], max_length=1)),
                ('is_primary_guardian', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.parent')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('exam_type', models.CharField(choices=[('CAT', 'Continous Assesment Test'), ('RAT', 'Random Assesment Test'), ('FINAL', 'Final Exam')], max_length=5)),
                ('academic_year', models.DateField()),
                ('term', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')])),
                ('date_entered', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.teacher'),
        ),
    ]
