# Generated by Django 5.2.7 on 2025-12-18 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentparent',
            name='student_id',
        ),
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='studentparent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='records.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='records.grade'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='records.student'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_left',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='records.grade'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('LEFT', 'Not enrolled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='records.student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='records.teacher'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='academic_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='records.student'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='records.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='performance',
            name='academic_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='date_entered',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='records.student'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='records.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='records.grade'),
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='is_primary_guardian',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='records.parent'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Enter name of the subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='records.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
