# Generated by Django 5.2.7 on 2025-12-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_studentparent_student_id_parent_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['date_enrolled']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['name'], 'verbose_name': 'Class details'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['academic_year', 'term']},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['full_name'], 'verbose_name': 'Parent details'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['payment_date']},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['academic_year', 'term'], 'verbose_name': 'Exam details'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Student details'},
        ),
        migrations.AlterModelOptions(
            name='studentparent',
            options={'verbose_name': 'Student-Parent join table'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Subject details'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name'], 'verbose_name': 'Teacher details'},
        ),
    ]
