# Generated by Django 5.2.7 on 2025-12-18 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_enrollment_options_alter_grade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(default='N/A', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='records.grade'),
        ),
    ]
