# Generated by Django 5.2.7 on 2025-12-18 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_parent_phone_number_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, default='N/A', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='records.grade'),
        ),
    ]
