# Generated by Django 5.2.7 on 2025-12-24 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_student_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['name'], 'verbose_name': 'Class detail'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['full_name', 'address', 'phone_number', 'email'], 'verbose_name': 'Parent detail'},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['academic_year', 'term'], 'verbose_name': 'Exam detail'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Student detail'},
        ),
        migrations.AlterModelOptions(
            name='studentparent',
            options={'ordering': ['student', 'parent', 'relationship_type', 'is_primary_guardian'], 'verbose_name': 'Student-Parent join'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Subject detail'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name'], 'verbose_name': 'Teacher detail'},
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin role'), ('Student', 'Student role'), ('Teacher', 'Teacher role'), ('Parent', 'Parent role')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
