# Generated by Django 5.2.7 on 2025-12-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_attendance_id_alter_enrollment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin role'), ('Student', 'Student role'), ('Teacher', 'Teacher role'), ('Parent', 'Parent role'), ('Pending', 'Registered, pending approval')], max_length=20),
        ),
    ]
